/**
 * GBA Pokémon-style Asset Loader for PixiJS
 * Auto-generated by generate-assets-gba.js
 */

import * as PIXI from 'pixi.js';

export interface SpriteSheetMeta {
  frameCount: number;
  frameWidth: number;
  frameHeight: number;
  rows: number;
  cols: number;
  totalWidth: number;
  totalHeight: number;
  style: string;
}

export interface NineSliceMeta {
  sliceWidth: number;
  sliceHeight: number;
  borderWidth: number;
  style: string;
}

/**
 * Load sprite sheet và tạo animation frames
 */
export async function loadSpriteSheet(
  assetPath: string,
  frameWidth: number,
  frameHeight: number,
  frameCount: number
): Promise<PIXI.Texture[]> {
  try {
    const texture = await PIXI.Assets.load(assetPath);
    
    // Kiểm tra kích thước texture
    if (!texture || !texture.baseTexture) {
      throw new Error(`Failed to load texture from: ${assetPath}`);
    }

    const baseWidth = texture.baseTexture.width;
    const baseHeight = texture.baseTexture.height;

    // Kiểm tra xem texture có đủ lớn không (không phải placeholder 1x1)
    if (baseWidth < frameWidth || baseHeight < frameHeight) {
      console.warn(`⚠️ Texture too small (${baseWidth}×${baseHeight}), expected at least ${frameWidth}×${frameHeight}. Using fallback.`);
      throw new Error(`Texture dimensions too small: ${baseWidth}×${baseHeight}`);
    }

    const frames: PIXI.Texture[] = [];
    const cols = Math.ceil(frameCount / 1);

    for (let i = 0; i < frameCount; i++) {
      const x = (i % cols) * frameWidth;
      const y = Math.floor(i / cols) * frameHeight;

      // Kiểm tra bounds
      if (x + frameWidth > baseWidth || y + frameHeight > baseHeight) {
        console.warn(`⚠️ Frame ${i} out of bounds, skipping`);
        continue;
      }
      
      frames.push(
        new PIXI.Texture(
          texture.baseTexture,
          new PIXI.Rectangle(x, y, frameWidth, frameHeight)
        )
      );
    }

    if (frames.length === 0) {
      throw new Error(`No valid frames extracted from: ${assetPath}`);
    }

    return frames;
  } catch (error) {
    console.error(`❌ Error loading sprite sheet ${assetPath}:`, error);
    throw error;
  }
}

/**
 * Load sprite sheet từ metadata file
 */
export async function loadSpriteSheetFromMeta(
  sheetPath: string
): Promise<{ textures: PIXI.Texture[]; meta: SpriteSheetMeta }> {
  try {
    const metaPath = sheetPath.replace('.png', '.sheet.json');
    const response = await fetch(metaPath);
    if (!response.ok) {
      throw new Error(`Failed to load metadata: ${metaPath}`);
    }
    const meta: SpriteSheetMeta = await response.json();
    
    const textures = await loadSpriteSheet(
      sheetPath,
      meta.frameWidth,
      meta.frameHeight,
      meta.frameCount
    );

    if (textures.length === 0) {
      throw new Error(`No textures loaded from: ${sheetPath}`);
    }

    return { textures, meta };
  } catch (error) {
    console.error('❌ Error loading sprite sheet:', error);
    // Return empty textures as fallback
    return { 
      textures: [], 
      meta: { 
        frameCount: 0, 
        frameWidth: 32, 
        frameHeight: 32, 
        rows: 1, 
        cols: 1, 
        totalWidth: 32, 
        totalHeight: 32, 
        style: 'GBA Pokémon Gen 3' 
      } 
    };
  }
}

/**
 * Tạo 9-slice sprite từ texture (GBA Pokémon dialogue box style)
 */
export async function createNineSliceSprite(
  assetPath: string
): Promise<PIXI.NineSlicePlane> {
  const texture = await PIXI.Assets.load(assetPath);
  try {
    const metaPath = assetPath.replace('.png', '.json');
    const response = await fetch(metaPath);
    if (!response.ok) {
      throw new Error(`Failed to load 9-slice metadata: ${metaPath}`);
    }
    const meta: NineSliceMeta = await response.json();

    return new PIXI.NineSlicePlane(
      texture,
      meta.borderWidth,
      meta.borderWidth,
      meta.borderWidth,
      meta.borderWidth
    );
  } catch (error) {
    console.error('Error loading 9-slice metadata:', error);
    // Fallback với border width mặc định
    return new PIXI.NineSlicePlane(texture, 16, 16, 16, 16);
  }
}

/**
 * Tạo animated sprite từ sprite sheet
 */
export function createAnimatedSprite(
  textures: PIXI.Texture[],
  animationSpeed: number = 0.1
): PIXI.AnimatedSprite {
  const sprite = new PIXI.AnimatedSprite(textures);
  sprite.animationSpeed = animationSpeed;
  sprite.loop = true;
  return sprite;
}

/**
 * Asset paths (GBA Pokémon style)
 */
export const ASSET_PATHS = {
  ui: {
    dialogueBox: '/assets/ui/frame_dialogue_box_9slice.png',
    inventorySlot: (rarity: 'common' | 'rare' | 'epic' | 'legendary' | 'cursed') =>
      `/assets/ui/frame_inventory_slot_${rarity}.png`,
    barHealthContainer: '/assets/ui/bar_health_container.png',
    barHealthFill: '/assets/ui/bar_health_fill.png',
    barOilContainer: '/assets/ui/bar_oil_container.png',
    barOilFill: '/assets/ui/bar_oil_fill.png',
    barSanityContainer: '/assets/ui/bar_sanity_container.png',
    barSanityFill: '/assets/ui/bar_sanity_fill.png',
    cursorHand: '/assets/ui/cursor_hand.png',
    iconArrowNext: '/assets/ui/icon_arrow_next.png',
    bgMenuPattern: '/assets/ui/bg_menu_pattern.png',
  },
  characters: {
    player: {
      mainSheet: '/assets/characters/player/spr_seeker_sheet.png',
      actionSheet: '/assets/characters/player/spr_seeker_action_sheet.png',
    },
    npcs: {
      merchantWhispers: '/assets/characters/npcs/spr_merchant_whispers_sheet.png',
      fallenQueen: '/assets/characters/npcs/spr_fallen_queen_sheet.png',
    },
    enemies: {
      mobPhantom: '/assets/characters/enemies/spr_mob_phantom_sheet.png',
      bossMirrorGuardian: '/assets/characters/enemies/spr_boss_mirror_guardian_sheet.png',
    },
  },
  items: {
    consumables: {
      oilFlask: '/assets/items/consumables/icon_oil_flask.png',
      oilFlaskGlowing: '/assets/items/consumables/icon_oil_flask_glowing.png',
      sanityPill: '/assets/items/consumables/icon_sanity_pill.png',
      regenSerum: '/assets/items/consumables/icon_regen_serum.png',
      wyrmOil: '/assets/items/consumables/icon_wyrm_oil.png',
    },
    weapons: {
      bladeScourgeLegendary: '/assets/items/weapons/icon_blade_scourge_legendary.png',
      chainsSunEaterEpic: '/assets/items/weapons/icon_chains_sun_eater_epic.png',
      daggerAncientEpic: '/assets/items/weapons/icon_dagger_ancient_epic.png',
    },
    armor: {
      armorSanguineCursed: '/assets/items/armor/icon_armor_sanguine_cursed.png',
      cloakGlitchCursed: '/assets/items/armor/icon_cloak_glitch_cursed.png',
      bootsRecursionEpic: '/assets/items/armor/icon_boots_recursion_epic.png',
    },
    artifacts: {
      memoryShard: '/assets/items/artifacts/icon_memory_shard.png',
      lensTruth: '/assets/items/artifacts/icon_lens_truth.png',
      soulboundScar: '/assets/items/artifacts/icon_soulbound_scar.png',
    },
  },
  tilesets: {
    dungeon: {
      floor: {
        cracked: '/assets/tilesets/dungeon/floor/tile_floor_00.png',
        bloodstained: '/assets/tilesets/dungeon/floor/tile_floor_04.png',
        moss: '/assets/tilesets/dungeon/floor/tile_floor_08.png',
      },
      walls: {
        brickDark: '/assets/tilesets/dungeon/walls/tile_wall_brick_dark.png',
        withWindow: '/assets/tilesets/dungeon/walls/tile_wall_window.png',
        withDoorway: '/assets/tilesets/dungeon/walls/tile_wall_doorway.png',
      },
    },
    props: {
      mirrorIntact: '/assets/tilesets/props/prop_mirror_intact.png',
      mirrorCracked: '/assets/tilesets/props/prop_mirror_cracked.png',
      mirrorShattered: '/assets/tilesets/props/prop_mirror_shattered.png',
      ruinPile: (index: number) => `/assets/tilesets/props/prop_ruin_pile_${String(index).padStart(2, '0')}.png`,
      crateStack: '/assets/tilesets/props/prop_crate_stack.png',
      barrelUpright: '/assets/tilesets/props/prop_barrel_upright.png',
      barrelSideways: '/assets/tilesets/props/prop_barrel_sideways.png',
      prisonGateClosed: '/assets/tilesets/props/prop_prison_gate_closed.png',
      prisonGateOpen: '/assets/tilesets/props/prop_prison_gate_open.png',
      skeleton: '/assets/tilesets/props/prop_skeleton.png',
      lanternPost: '/assets/tilesets/props/prop_lantern_post.png',
      chestClosed: '/assets/tilesets/props/prop_chest_closed.png',
      chestOpen: '/assets/tilesets/props/prop_chest_open.png',
    },
  },
  fx: {
    glitchStatic: '/assets/fx/fx_glitch_static_sheet.png',
    lightGlowAmber: '/assets/fx/fx_light_glow_amber_sheet.png',
    fogWar: '/assets/fx/fx_fog_war_sheet.png',
  },
} as const;
