/**
 * Auto-generated asset paths
 * Generated by generate-assets.js
 * DO NOT EDIT MANUALLY - Regenerate when assets change
 */

export const ASSET_PATHS = {
  ui: {
    frameDialogueBox: '/assets/ui/frame_dialogue_box.png',
    frameInventorySlot: '/assets/ui/frame_inventory_slot.png',
    frameInventorySlotCommon: '/assets/ui/frame_inventory_slot_common.png',
    frameInventorySlotRare: '/assets/ui/frame_inventory_slot_rare.png',
    frameInventorySlotEpic: '/assets/ui/frame_inventory_slot_epic.png',
    frameInventorySlotLegendary: '/assets/ui/frame_inventory_slot_legendary.png',
    frameInventorySlotCursed: '/assets/ui/frame_inventory_slot_cursed.png',
    barHealthContainer: '/assets/ui/bar_health_container.png',
    barHealthFill: '/assets/ui/bar_health_fill.png',
    barOilContainer: '/assets/ui/bar_oil_container.png',
    barOilFill: '/assets/ui/bar_oil_fill.png',
    barSanityContainer: '/assets/ui/bar_sanity_container.png',
    barSanityFill: '/assets/ui/bar_sanity_fill.png',
    cursorHand: '/assets/ui/cursor_hand.png',
    iconArrowNext: '/assets/ui/icon_arrow_next.png',
    bgMenuPattern: '/assets/ui/bg_menu_pattern.png',
  },
  characters: {
    player: {
      seekerIdleDown: '/assets/characters/player/spr_seeker_idle_down.png',
      seekerIdleUp: '/assets/characters/player/spr_seeker_idle_up.png',
      seekerIdleLeft: '/assets/characters/player/spr_seeker_idle_left.png',
      seekerIdleRight: '/assets/characters/player/spr_seeker_idle_right.png',
      seekerWalkDown: '/assets/characters/player/spr_seeker_walk_down.png',
      seekerWalkUp: '/assets/characters/player/spr_seeker_walk_up.png',
      seekerWalkLeft: '/assets/characters/player/spr_seeker_walk_left.png',
      seekerWalkRight: '/assets/characters/player/spr_seeker_walk_right.png',
      seekerAction: '/assets/characters/player/spr_seeker_action.png',
    },
    npcs: {
      merchantWhispers: '/assets/characters/npcs/spr_merchant_whispers.png',
      fallenQueen: '/assets/characters/npcs/spr_fallen_queen.png',
    },
    enemies: {
      mobPhantom: '/assets/characters/enemies/spr_mob_phantom.png',
      bossMirrorGuardian: '/assets/characters/enemies/spr_boss_mirror_guardian.png',
    },
  },
  items: {
    consumables: {
      oilFlask: '/assets/items/consumables/icon_oil_flask.png',
      sanityPill: '/assets/items/consumables/icon_sanity_pill.png',
      wyrmOil: '/assets/items/consumables/icon_wyrm_oil.png',
      regenSerum: '/assets/items/consumables/icon_regen_serum.png',
    },
    weapons: {
      bladeScourgeLegendary: '/assets/items/weapons/icon_blade_scourge_legendary.png',
      chainsSunEaterEpic: '/assets/items/weapons/icon_chains_sun_eater_epic.png',
      daggerAncientEpic: '/assets/items/weapons/icon_dagger_ancient_epic.png',
    },
    armor: {
      armorSanguineCursed: '/assets/items/armor/icon_armor_sanguine_cursed.png',
      cloakGlitchCursed: '/assets/items/armor/icon_cloak_glitch_cursed.png',
      bootsRecursionEpic: '/assets/items/armor/icon_boots_recursion_epic.png',
    },
    artifacts: {
      memoryShard: '/assets/items/artifacts/icon_memory_shard.png',
      lensTruth: '/assets/items/artifacts/icon_lens_truth.png',
      soulboundScar: '/assets/items/artifacts/icon_soulbound_scar.png',
    },
  },
  tilesets: {
    dungeonFloor01: '/assets/tilesets/tile_dungeon_floor_01.png',
    dungeonFloorCracked: '/assets/tilesets/tile_dungeon_floor_cracked.png',
    wallBrickDark: '/assets/tilesets/tile_wall_brick_dark.png',
    lanternPost: '/assets/tilesets/prop_lantern_post.png',
    mirrorBroken: '/assets/tilesets/prop_mirror_broken.png',
    chestClosed: '/assets/tilesets/prop_chest_closed.png',
    chestOpen: '/assets/tilesets/prop_chest_open.png',
  },
  fx: {
    glitchStatic: '/assets/fx/fx_glitch_static.png',
    lightGlowAmber: '/assets/fx/fx_light_glow_amber.png',
    fogWar: '/assets/fx/fx_fog_war.png',
  },
} as const;

export type AssetPath = typeof ASSET_PATHS[keyof typeof ASSET_PATHS][keyof typeof ASSET_PATHS[keyof typeof ASSET_PATHS]];
